{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName | default .Chart.Name | quote }}
  labels:
    app: app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: {{ .Values.secret.secretType | default Opaque }}
data:
{{- range $name, $value := .Values.secrets }}
{{- if not (empty $value) }}
   {{ $name }}: {{ $value | quote }}
{{- end}}
{{- end }}
{{- end }}