name: Helm Chart Release

on:
  push:
    paths-ignore:
      - ".github/workflows/*"
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Update Chart Version
        id: update_version
        run: |
          current_version=$(awk '/version:/ {print $2}' charts/standard-app/Chart.yaml)
          increment_version="0.1.0"
          IFS='.' read -ra current_parts <<< "$current_version"
          IFS='.' read -ra increment_parts <<< "$increment_version"

          first=$((current_parts[0] + increment_parts[0]))
          second=$((current_parts[1] + increment_parts[1]))
          third=$((current_parts[2] + increment_parts[2]))
          echo $first
          echo $second
          echo $third
          new_version="$first.$second.$third"
          echo $new_version

          sed "s/version:.*/version: $new_version/" charts/standard-app/Chart.yaml > tmpfile
          mv tmpfile charts/standard-app/Chart.yaml
          cat charts/standard-app/Chart.yaml

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
